twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
            blogposts_directory: '%blogposts_directory%'
            projects_directory: '%projects_directory%'
            scenarios_directory: '%scenarios_directory%'
            partners_directory: '%partners_directory%'

when@test:
    twig:
        strict_variables: true
