twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
            persons_directory: '%persons_directory%'
            blogposts_directory: '%blogposts_directory%'
            projects_directory: '%projects_directory%'
            resources_directory: '%resources_directory%'

when@test:
    twig:
        strict_variables: true
